In [1]:
import pandas as pd

In [2]:
penjualan = pd.read_csv('penjualan50.csv')

In [3]:
data = penjualan.copy()

In [4]:
target = 'nama_produk'

In [5]:
encode = ['jenis_kelamin']

In [6]:
data

,nama_produk,durasi,jumlah,usia,diskon_shopee,diskon_penjual,jenis_kelamin,cashback
0,youtube,4,1,23,0,0,Wanita,0
1,spotify,4,1,38,0,0,Pria,0
2,spotify,1,1,29,0,0,Pria,0
3,youtube,4,1,29,0,0,Wanita,0
4,youtube,4,1,18,0,0,Pria,0
...,...,...,...,...,...,...,...,...
1642,youtube,1,6,22,0,0,Pria,0
1643,netflix,1,1,18,0,0,Wanita,0
1644,netflix,1,1,30,0,0,Wanita,0
1645,youtube,1,1,22,0,0,Pria,0
1646,youtube,1,1,18,0,0,Pria,0

In [7]:
for col in encode:
    dummy = pd.get_dummies(data[col], prefix=col)
    data = pd.concat([data,dummy], axis=1)
    del data[col]

In [8]:
data

,nama_produk,durasi,jumlah,usia,diskon_shopee,diskon_penjual,cashback,jenis_kelamin_Pria,jenis_kelamin_Wanita
0,youtube,4,1,23,0,0,0,0,1
1,spotify,4,1,38,0,0,0,1,0
2,spotify,1,1,29,0,0,0,1,0
3,youtube,4,1,29,0,0,0,0,1
4,youtube,4,1,18,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...
1642,youtube,1,6,22,0,0,0,1,0
1643,netflix,1,1,18,0,0,0,0,1
1644,netflix,1,1,30,0,0,0,0,1
1645,youtube,1,1,22,0,0,0,1,0
1646,youtube,1,1,18,0,0,0,1,0

In [9]:
target_mapper = {'spotify':0, 'youtube':1, 'netflix':2}

In [10]:
def target_encode(val):
    return target_mapper[val]

In [11]:
data['nama_produk'] = data['nama_produk'].apply(target_encode)
# mengubah nilai dalam nama_produk
data

,nama_produk,durasi,jumlah,usia,diskon_shopee,diskon_penjual,cashback,jenis_kelamin_Pria,jenis_kelamin_Wanita
0,1,4,1,23,0,0,0,0,1
1,0,4,1,38,0,0,0,1,0
2,0,1,1,29,0,0,0,1,0
3,1,4,1,29,0,0,0,0,1
4,1,4,1,18,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...
1642,1,1,6,22,0,0,0,1,0
1643,2,1,1,18,0,0,0,0,1
1644,2,1,1,30,0,0,0,0,1
1645,1,1,1,22,0,0,0,1,0
1646,1,1,1,18,0,0,0,1,0

data

In [12]:
x = data.drop('nama_produk',axis=1)
y = data['nama_produk']
# memisahkan
# hilangkan kolom 1

In [13]:
x

,durasi,jumlah,usia,diskon_shopee,diskon_penjual,cashback,jenis_kelamin_Pria,jenis_kelamin_Wanita
0,4,1,23,0,0,0,0,1
1,4,1,38,0,0,0,1,0
2,1,1,29,0,0,0,1,0
3,4,1,29,0,0,0,0,1
4,4,1,18,0,0,0,1,0
...,...,...,...,...,...,...,...,...
1642,1,6,22,0,0,0,1,0
1643,1,1,18,0,0,0,0,1
1644,1,1,30,0,0,0,0,1
1645,1,1,22,0,0,0,1,0
1646,1,1,18,0,0,0,1,0

In [14]:
y

0       1
1       0
2       0
3       1
4       1
       ..
1642    1
1643    2
1644    2
1645    1
1646    1
Name: nama_produk, Length: 1647, dtype: int64

In [15]:
#model naive bayes klasifikasi NBC
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x,y)

GaussianNB()

In [16]:
#menyimpan model NBC
import pickle
pickle.dump(model, open('modelNBC_penjualan.pkl', 'wb'))